Manual commit of gh-pages

diff --git a/.github/workflows/actions_test.yml b/.github/workflows/actions_test.yml
--- a/.github/workflows/actions_test.yml
+++ b/.github/workflows/actions_test.yml
@@ -1,6 +1,6 @@
 name: Python Package using Conda
 
-on: [push]
+on: [push, pull_request]
 
 jobs:
   build-linux:
@@ -61,11 +61,23 @@ jobs:
     - name: Build documentation
       run: |
         mkdocs build
-    - name: Deploy docs to GitHub Pages
-      uses: peaceiris/actions-gh-pages@v3
-      with: 
-        github_token: $
-        publish_dir: ./site
-      
+    - name: Commit documentation changes
+      run: |
+        echo "Cloning from $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git"
+        git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git --branch gh-pages --single-branch gh-pages
+        cp -r doc/_build/html/* gh-pages/
+        cd gh-pages
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add .
+        git commit -m "Update documentation" -a || true
+        # The above command will fail if no changes were present, so we ignore
+        # the return code.
+    - name: Push changes
+      uses: ad-m/github-push-action@master
+      with:
+        branch: gh-pages
+        directory: gh-pages
+        github_token: ${{ secrets.GITHUB_TOKEN }}
       
       
